language: node_js
node_js:
  - stable
script: npm run build
after_success:
  - surge --project ./build/ --domain kottans.surge.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: source
branches:
  only:
  - source

