language: node_js
node_js:
  - stable
script: npm run build
after_success:
  - surge --project ./build/ --domain kottans.surge.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

