export default {
	UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',
	UPDATE_LIST_OF_REPOS: 'UPDATE_LIST_OF_REPOS',
	LOADING: 'LOADING',
	ERROR: 'ERROR',
	DIALOG_VISIBLE: 'DIALOG_VISIBLE',
	DIALOG_INFO: 'DIALOG_INFO',
	VIEW_CONFIG: 'VIEW_CONFIG'
};

