export default {
	UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',
	UPDATE_LIST_OF_REPOS: 'UPDATE_LIST_OF_REPOS',
	LOADING: 'LOADING',
	ERROR: 'ERROR',
	DIALOG_VISIBLE: 'DIALOG_VISIBLE',
	DIALOG_INFO: 'DIALOG_INFO',
	VIEW_CONFIG_REPLACE: 'VIEW_CONFIG_REPLACE',
	VIEW_CONFIG_UPDATE: 'VIEW_CONFIG_UPDATE',
	SHOW_MORE_ITEMS: 'SHOW_MORE_ITEMS'
};

